runtime: nodejs20
entrypoint: npm run start

instance_class: F2

build_env_variables:
  NODE_ENV: production
  NEXT_TELEMETRY_DISABLED: "1"
  NEXTAUTH_URL: "https://cs144-25s-tzantchev.uw.r.appspot.com"
  MONGO_URI: "${MONGO_URI}"
  AUTH_SECRET: "${AUTH_SECRET}"
  AUTH_GOOGLE_ID: "${AUTH_GOOGLE_ID}"
  AUTH_GOOGLE_SECRET: "${AUTH_GOOGLE_SECRET}"
  TAVILY_API_KEY: "${TAVILY_API_KEY}"
  OPENAI_API_KEY: "${OPENAI_API_KEY}"

env_variables:
  NODE_ENV: production
  NEXT_TELEMETRY_DISABLED: "1"
  NEXTAUTH_URL: "https://cs144-25s-tzantchev.uw.r.appspot.com"
  MONGO_URI: "${MONGO_URI}"
  AUTH_SECRET: "${AUTH_SECRET}"
  AUTH_GOOGLE_ID: "${AUTH_GOOGLE_ID}"
  AUTH_GOOGLE_SECRET: "${AUTH_GOOGLE_SECRET}"
  TAVILY_API_KEY: "${TAVILY_API_KEY}"
  OPENAI_API_KEY: "${OPENAI_API_KEY}"

handlers:
  - url: /.*
    script: auto
    secure: always
